import { Heart } from "@/components/icons/heart";
import Navbar from "@/components/navbar";
import { Button } from "@base-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function SideMenu() {
  return (
    <div className="pb-12 w-1/5">
      <div className="space-y-4 py-4">
        <div className="px-3 py-4">
          <h2 className="mb-4 pl-2 text-2xl font-bold tracking-tight">
            Manage
          </h2>
          <div className="flex flex-col gap-2">
            <Link href="/gallery">
              <Button className="w-full flex justify-start gap-2 hover:bg-white hover:text-black rounded-lg px-1 py-2">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-6 h-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 001.5-1.5V6a1.5 1.5 0 00-1.5-1.5H3.75A1.5 1.5 0 002.25 6v12a1.5 1.5 0 001.5 1.5zm10.5-11.25h.008v.008h-.008V8.25zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"
                  />
                </svg>
                Gallery
              </Button>
            </Link>
            <Link href="/favorites">
              <Button className="w-full justify-start flex gap-2 hover:bg-white hover:text-black rounded-lg px-1 py-2">
                <Heart />
                Favorites
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex items-center h-24">
          <div className="flex h-16 items-center">
            <Navbar />
          </div>
        </div>
        <div className="flex">
          <SideMenu />
          <div className="w-5/6 px-32 py-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
